#[ 
  ReliQ lattice field theory framework: https://github.com/reliq-lft/ReliQ
  Source file: src/classes/classconstructors.nim
  Contact: reliq-lft@proton.me

  Author: Curtis Taylor Peterson <curtistaylorpetersonwork@gmail.com>

  MIT License
  
  Copyright (c) 2025 reliq-lft
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]#

## Handle ``init`` methods for classes.
##
## Chapel semantics:
##   - A compiler-generated default initializer sets fields to their default
##     values and allocates the ``ref object``.
##   - Users may provide their own ``init()``.
##   - ``new ClassName(args)`` creates a class instance.
##   - For inherited classes, parent fields are initialized first (via
##     ``super.init()``); if the user doesn't call it, the compiler inserts
##     a zero-argument ``super.init()`` call at the start.
##   - A ``postinit()`` method, if defined, is called after ``init()``.
##
## We generate:
##   1. A default ``init()`` if no user-defined one exists.
##   2. Field-default-value injection at the top of every ``init``.
##   3. Convenience constructor procs: ``ClassName.init(...)``,
##      ``newClassName(...)``, ``ClassName.new(...)``.
## 
## Architecture adapted from jjv360/nim-classes 
## 
## MIT License
##  
## Copyright (c) 2021 jjv360
##  
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##  
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
## WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
## CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

{.used.}

import std/[macros]
import std/[tables]

import classinternal
import classmethods
import classvar
import classutils

#[ Insert auto-generated init ]#

proc insertAutogeneratedInits(classDef: ClassDescription) =
  var hasInit = false
  for m in classDef.methods.definitions:
    if $m.definition.name == "init":
      hasInit = true
      break

  if not hasInit:
    var m = ClassMethod()
    m.definition = quote do:
      method init()
    m.body = newStmtList()
    classDef.methods.definitions.add(m)

#[ Inject field defaults into init bodies ]#

proc setupVarsInInit(classDef: ClassDescription) =
  # Build code that sets every field with a default value.
  # For inherited classes, we also set parent field defaults.
  var initCode = newStmtList()

  # First, set parent field defaults (recursively up the inheritance chain)
  proc collectParentDefaults(parentName: NimNode, code: NimNode) =
    if parentName == nil or $parentName == "RootObj":
      return
    let parentDef = classDefinitionFor(parentName)
    if parentDef == nil:
      return
    # Recurse to grandparent first
    collectParentDefaults(parentDef.parentName, code)
    # Then add this parent's field defaults
    for varDef in parentDef.vars.definitions:
      let valueNode = varDef.definition[2]
      if valueNode.kind == nnkEmpty:
        continue
      let nameDef = varDef.definition.variableName
      code.add(quote do:
        this.`nameDef` = `valueNode`
      )

  collectParentDefaults(classDef.parentName, initCode)

  # Then set this class's own field defaults
  for varDef in classDef.vars.definitions:
    let valueNode = varDef.definition[2]
    if valueNode.kind == nnkEmpty:
      continue
    let nameDef = varDef.definition.variableName
    initCode.add(quote do:
      this.`nameDef` = `valueNode`
    )

  for methodDef in classDef.methods.definitions:
    if $methodDef.definition.name != "init":
      continue
    if methodDef.isStatic or methodDef.insertUnmodified:
      continue

    # Set return type to the full class type
    methodDef.definition.params[0] = classDef.fullType

    # For ref objects, we need to allocate with `new` first,
    # then assign fields. The init body becomes:
    #   var this = ClassName()   ← `new` allocation
    #   this.field1 = default1
    #   ... user init body ...
    #   return this
    #
    # But since `this` is injected as the first parameter by classmethods,
    # we instead make init a proc that receives `this` and returns it.
    # The convenience constructors allocate and call init.

    # Return `this` at the end
    methodDef.body.add(quote do:
      return this
    )

    # Inject field defaults at the top of the body
    if initCode.len > 0:
      methodDef.body.insert(0, initCode)

#[ Generate convenience constructors ]#

proc generateExtraInits(classDef: ClassDescription) =
  var newItems: seq[ClassMethod] = @[]
  for methodDef in classDef.methods.definitions:
    if $methodDef.definition.name != "init":
      continue

    let classType = classDef.fullType
    let underscore = ident"_"

    # Check if there's a postinit method
    var hasPostinit = false
    for m in classDef.methods.definitions:
      if $m.definition.name == "postinit":
        hasPostinit = true
        break

    # Helper to build the constructor body:
    #   var o = ClassName()    ← ref object allocation
    #   o = o.init(args...)    ← call user init
    #   o.postinit()           ← optional
    #   return o
    proc makeConstructorBody(argNames: seq[NimNode]): NimNode =
      let body = newStmtList()
      # Allocate the ref object
      body.add(newVarStmt(ident"o", newCall(classType)))
      # Call init
      let initCall = newCall(newDotExpr(ident"o", ident"init"))
      for arg in argNames:
        initCall.add(arg)
      body.add(newAssignment(ident"o", initCall))
      # Call postinit if it exists
      if hasPostinit:
        body.add(newCall(newDotExpr(ident"o", ident"postinit")))
      body.add(newNimNode(nnkReturnStmt).add(ident"o"))
      return body

    # Collect user param names
    var paramNames: seq[NimNode] = @[]
    traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
        typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
      paramNames.add(nameNode)
    )

    # 1. ClassName.init(...)  →  static proc
    block:
      let initName = ident"init"
      let m = ClassMethod()
      m.insertUnmodified = true
      m.definition = quote do:
        proc `initName`*(`underscore`: typedesc[`classType`]): `classType`
      m.body = makeConstructorBody(paramNames)
      m.definition.addGenericParams(classDef)

      traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
          typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
        m.definition.params.add(newIdentDefs(nameNode, typeNode, newEmptyNode()))
      )
      newItems.add(m)

    # 2. newClassName(...)
    block:
      let newName = ident("new" & $classDef.name)
      let m = ClassMethod()
      m.insertUnmodified = true
      m.definition = quote do:
        proc `newName`*(): `classType`
      m.body = makeConstructorBody(paramNames)
      m.definition.addGenericParams(classDef)

      traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
          typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
        m.definition.params.add(newIdentDefs(nameNode, typeNode, newEmptyNode()))
      )
      newItems.add(m)

    # 3. ClassName.new(...)
    block:
      let newIdent = ident"new"
      let m = ClassMethod()
      m.insertUnmodified = true
      m.definition = quote do:
        proc `newIdent`*(`underscore`: typedesc[`classType`]): `classType`
      m.body = makeConstructorBody(paramNames)
      m.definition.addGenericParams(classDef)

      traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
          typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
        m.definition.params.add(newIdentDefs(nameNode, typeNode, newEmptyNode()))
      )
      newItems.add(m)

  for m in newItems:
    classDef.methods.definitions.add(m)

#[ Register ]#

static:
  classCompilerHooks.add(proc(stage: ClassCompilerStage, classDef: ClassDescription) =
    if stage == ClassAddExtraDefinitions: insertAutogeneratedInits(classDef)
    if stage == ClassAddExtraDefinitions: generateExtraInits(classDef)
    if stage == ClassModifyDefinitions: setupVarsInInit(classDef)
  )
