#[ 
  ReliQ lattice field theory framework: https://github.com/reliq-lft/ReliQ
  Source file: src/record/recordconstructors.nim
  Contact: reliq-lft@proton.me

  Author: Curtis Taylor Peterson <curtistaylorpetersonwork@gmail.com>

  MIT License
  
  Copyright (c) 2025 reliq-lft
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]#

## Handle `init` methods for records.
##
## Chapel semantics:
##   - A compiler-generated default initializer sets fields to their
##     default values.
##   - Users may provide their own `init()`.
##   - `new RecordName(args)` creates a record value.
##
## We generate:
##   1. A default `init()` if no user-defined one exists.
##   2. Field-default-value injection at the top of every `init`.
##   3. Convenience constructor procs: `RecordName.init(...)`,
##      `newRecordName(...)`, `RecordName.new(...)`.
##
## Adapted from jjv360/nim-classes
## 
## MIT License
##  
## Copyright (c) 2021 jjv360
##  
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in all
## copies or substantial portions of the Software.
##  
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
## WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
## CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

{.used.}

import std/[macros]
import std/[tables]

import recordinternal
import recordmethods
import recordvar
import recordutils

#[ Insert auto-generated init ]#

proc insertAutogeneratedInits(recDef: RecordDescription) =
  var hasInit = false
  for m in recDef.methods.definitions:
    if $m.definition.name == "init":
      hasInit = true
      break

  if not hasInit:
    var m = RecordMethod()
    m.definition = quote do:
      method init()
    m.body = newStmtList()
    recDef.methods.definitions.add(m)

#[ Inject field defaults into init bodies ]#

proc setupVarsInInit(recDef: RecordDescription) =
  # Build code that sets every field with a default value
  var initCode = newStmtList()
  for varDef in recDef.vars.definitions:
    let valueNode = varDef.definition[2]
    if valueNode.kind == nnkEmpty:
      continue
    let nameDef = varDef.definition.variableName
    initCode.add(quote do:
      this.`nameDef` = `valueNode`
    )

  for methodDef in recDef.methods.definitions:
    if $methodDef.definition.name != "init":
      continue
    if methodDef.isStatic or methodDef.insertUnmodified:
      continue

    # Set return type to the full record type (Name or Name[T,...])
    methodDef.definition.params[0] = recDef.fullType

    # Return `this` at the end
    methodDef.body.add(quote do:
      return this
    )

    # Inject field defaults at the top of the body
    if initCode.len > 0:
      methodDef.body.insert(0, initCode)

#[ Generate convenience constructors ]#

proc generateExtraInits(recDef: RecordDescription) =
  var newItems: seq[RecordMethod] = @[]
  for methodDef in recDef.methods.definitions:
    if $methodDef.definition.name != "init":
      continue

    let classType = recDef.fullType
    let underscore = ident"_"

    # 1. RecordName.init(...)  →  static proc
    block:
      let initName = ident"init"
      let m = RecordMethod()
      m.insertUnmodified = true
      m.definition = quote do:
        proc `initName`*(`underscore`: typedesc[`classType`]): `classType`
      m.body = quote do:
        var o: `classType`
        discard o.init()
        return o
      m.definition.addGenericParams(recDef)

      # Forward user-defined init params
      traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
          typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
        m.definition.params.add(newIdentDefs(nameNode, typeNode, identDef[^1]))
        m.body[1][0].add(nameNode)  # DiscardStmt[0] = the o.init() call
      )
      newItems.add(m)

    # 2. newRecordName(...)
    block:
      let newName = ident("new" & $recDef.name)
      let m = RecordMethod()
      m.insertUnmodified = true
      m.definition = quote do:
        proc `newName`*(): `classType`
      m.body = quote do:
        var o: `classType`
        discard o.init()
        return o
      m.definition.addGenericParams(recDef)

      traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
          typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
        m.definition.params.add(newIdentDefs(nameNode, typeNode, identDef[^1]))
        m.body[1][0].add(nameNode)  # DiscardStmt[0] = the o.init() call
      )
      newItems.add(m)

    # 3. RecordName.new(...)
    block:
      let newIdent = ident"new"
      let m = RecordMethod()
      m.insertUnmodified = true
      m.definition = quote do:
        proc `newIdent`*(`underscore`: typedesc[`classType`]): `classType`
      m.body = quote do:
        var o: `classType`
        discard o.init()
        return o
      m.definition.addGenericParams(recDef)

      traverseParams(methodDef.definition, proc(idx: int, nameNode: NimNode,
          typeNode: NimNode, identDef: NimNode, identDefIdx: int) =
        m.definition.params.add(newIdentDefs(nameNode, typeNode, identDef[^1]))
        m.body[1][0].add(nameNode)  # DiscardStmt[0] = the o.init() call
      )
      newItems.add(m)

  for m in newItems:
    recDef.methods.definitions.add(m)

#[ Register ]#

static:
  recordCompilerHooks.add(proc(stage: RecordCompilerStage, recDef: RecordDescription) =
    if stage == RecordAddExtraDefinitions: insertAutogeneratedInits(recDef)
    if stage == RecordAddExtraDefinitions: generateExtraInits(recDef)
    if stage == RecordModifyDefinitions: setupVarsInInit(recDef)
  )
