#[ 
  ReliQ lattice field theory framework: https://github.com/reliq-lft/ReliQ
  Source file: src/record/recordcopy.nim
  Contact: reliq-lft@proton.me

  Author: Curtis Taylor Peterson <curtistaylorpetersonwork@gmail.com>

  MIT License
  
  Copyright (c) 2025 reliq-lft
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
]#

## Generate Chapel-style copy initialization and assignment for records.
##
## Chapel semantics:
##   - Copy initialization (`init=`): creates a new record by copying
##     each field from the source.
##   - Assignment (`=`): copies each field from rhs to lhs.
##   - These are compiler-generated by default but can be overridden.

{.used.}

import std/macros
import ./recordinternal
import ./recordvar
import ./recordutils

# ---------------------------------------------------------------------------
# Generate copy/assignment procs
# ---------------------------------------------------------------------------

proc generateCopyOps(recDef: RecordDescription) =
  let className = recDef.fullType

  # --- Copy proc: `copyInit(other: T): T` ---
  let resIdent = ident"res"
  let otherIdent = ident"other"
  var copyBody = newStmtList()
  copyBody.add(newVarStmt(resIdent, newCall(className)))
  for varDef in recDef.vars.definitions:
    let name = varDef.definition.variableName
    copyBody.add(newAssignment(
      newDotExpr(resIdent, name),
      newDotExpr(otherIdent, name)))
  copyBody.add(newNimNode(nnkReturnStmt).add(resIdent))

  let copyProc = quote do:
    proc copyInit*(`otherIdent`: `className`): `className` =
      `copyBody`
  copyProc.addGenericParams(recDef)
  recDef.body.add(copyProc)

  # --- copyFrom helper ---
  let lhsIdent = ident"lhs"
  let rhsIdent = ident"rhs"
  var assignBody = newStmtList()
  for varDef in recDef.vars.definitions:
    let name = varDef.definition.variableName
    assignBody.add(newAssignment(
      newDotExpr(lhsIdent, name),
      newDotExpr(rhsIdent, name)))

  let copyFromProc = quote do:
    proc copyFrom*(`lhsIdent`: var `className`, `rhsIdent`: `className`) =
      `assignBody`
  copyFromProc.addGenericParams(recDef)
  recDef.body.add(copyFromProc)

# ---------------------------------------------------------------------------
# Register
# ---------------------------------------------------------------------------

static:
  recordCompilerHooks.add(proc(stage: RecordCompilerStage, recDef: RecordDescription) =
    if stage == RecordGenerateCode: generateCopyOps(recDef)
  )
